/****
This SQL script was generated by the Configure Data Synchronization
dialog box. This script contains statements that create the
change-tracking columns, deleted-items table, and triggers on the
server database. These database objects are required by Synchronization
Services to successfully synchronize data between client and server
databases. For more information, see the
‘How to: Configure a Database Server for Synchronization’ topic in Help.
****/


IF @@TRANCOUNT > 0
set ANSI_NULLS ON 
set QUOTED_IDENTIFIER ON 

GO
BEGIN TRANSACTION;


IF @@TRANCOUNT > 0
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USERS_SPECIALITES_Tombstone]')) 
BEGIN 
CREATE TABLE [dbo].[USERS_SPECIALITES_Tombstone]( 
    [ANNEE_UNIVERSITAIRE] Int NOT NULL,
    [ID_SPECIALITE] Int NOT NULL,
    [ID_USER] Int NOT NULL,
    [ID_MATIERE] Int NOT NULL,
    [ID_GROUPE] Int NOT NULL,
    [DeletionDate] DateTime NULL
)END 

GO
IF @@ERROR <> 0 
     ROLLBACK TRANSACTION;


IF @@TRANCOUNT > 0
ALTER TABLE [dbo].[USERS_SPECIALITES_Tombstone] ADD CONSTRAINT [PKDEL_USERS_SPECIALITES_Tombstone_ANNEE_UNIVERSITAIREID_SPECIALITEID_USERID_MATIEREID_GROUPE]
   PRIMARY KEY CLUSTERED
    ([ANNEE_UNIVERSITAIRE], [ID_SPECIALITE], [ID_USER], [ID_MATIERE], [ID_GROUPE])
GO
IF @@ERROR <> 0 
     ROLLBACK TRANSACTION;


IF @@TRANCOUNT > 0
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USERS_SPECIALITES_DeletionTrigger]') AND type = 'TR') 
   DROP TRIGGER [dbo].[USERS_SPECIALITES_DeletionTrigger] 

GO
CREATE TRIGGER [dbo].[USERS_SPECIALITES_DeletionTrigger] 
    ON [USERS_SPECIALITES] 
    AFTER DELETE 
AS 
SET NOCOUNT ON 
UPDATE [dbo].[USERS_SPECIALITES_Tombstone] 
    SET [DeletionDate] = GETUTCDATE() 
    FROM deleted 
    WHERE deleted.[ANNEE_UNIVERSITAIRE] = [USERS_SPECIALITES_Tombstone].[ANNEE_UNIVERSITAIRE] 
    AND deleted.[ID_SPECIALITE] = [USERS_SPECIALITES_Tombstone].[ID_SPECIALITE] 
    AND deleted.[ID_USER] = [USERS_SPECIALITES_Tombstone].[ID_USER] 
    AND deleted.[ID_MATIERE] = [USERS_SPECIALITES_Tombstone].[ID_MATIERE] 
    AND deleted.[ID_GROUPE] = [USERS_SPECIALITES_Tombstone].[ID_GROUPE] 
IF @@ROWCOUNT = 0 
BEGIN 
    INSERT INTO [dbo].[USERS_SPECIALITES_Tombstone] 
    ([ANNEE_UNIVERSITAIRE], [ID_SPECIALITE], [ID_USER], [ID_MATIERE], [ID_GROUPE], DeletionDate)
    SELECT [ANNEE_UNIVERSITAIRE], [ID_SPECIALITE], [ID_USER], [ID_MATIERE], [ID_GROUPE], GETUTCDATE()
    FROM deleted 
END 

GO
IF @@ERROR <> 0 
     ROLLBACK TRANSACTION;
COMMIT TRANSACTION;
